# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login\activity_integralLog.yaml


import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from testcases.login.login_testcase_test import TestCaseLoginTestcase as LoginTestcase


class TestCaseActivityIntegrallog(HttpRunner):

    config = (
        Config("查询积分明细")
        .variables(**{"device": "${ENV(device_type)}"})
        .base_url("${ENV(url)}")
    )

    teststeps = [
        Step(RunTestCase("登录").call(LoginTestcase).export(*["token"])),
        Step(
            RunRequest("查询")
            .post("/index.php/activity/integralLog")
            .with_json(
                {
                    "device_type": "$device",
                    "page": 1,
                    "limit": 1,
                    "Authorization": "$token",
                }
            )
            .validate()
            .assert_equal("body.code", 1000)
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseActivityIntegrallog().test_start()
