# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login\login_testcase.yaml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginTestcase(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"name-pas": "${P(data/login_data.csv)}"})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("login")
        .variables(**{"pas": "${ENV(password)}", "device": "${ENV(device_type)}"})
        .base_url("${ENV(url)}")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/index.php/login/submit")
            .with_json(
                {"username": "$name", "password": "$pas", "device_type": "$device"}
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("body.code", 1000)
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginTestcase().test_start()
